apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: posts-api
spec:
  replicas: 1
  selector:
    matchLabels: # service will match (forward) to pod under tagged `posts-api`
      app.kubernetes.io/name: posts-api
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels: # same as .spec.selector.matchLabels
        app.kubernetes.io/name: posts-api 
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: posts-api
        image: {{ .Values.api.image }}
        env:
        - name: DD_TRACE_AGENT_PORT
          value: "8126"
        - name: DD_AGENT_HOST
          value: "datadog-agent"
        - name: DD_TRACE_HOST
          value: "datadog-agent"
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: posts-api
  labels:
    {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3001
    name: http
  selector: # labels to match pods
    app.kubernetes.io/name: posts-api
    app.kubernetes.io/instance: {{ .Release.Name }}

